'use client';

import { useActionState, useState, useTransition } from 'react';
import {
  startTotpEnrollment,
  verifyTotp,
  type EnrollState,
  type VerifyState,
} from '@/server/actions/mfa';
import { Alert } from '@/ui/Alert';
import { Button } from '@/ui/Button';
import { TextField } from '@/ui/TextField';

const initialVerify: VerifyState = { status: 'idle' };

export function MfaVerify({ factorId, next }: { factorId: string; next: string }) {
  const [state, action, pending] = useActionState(verifyTotp, initialVerify);
  return (
    <form action={action} className="flex flex-col gap-4" noValidate>
      {state.status === 'error' ? <Alert tone="error">{state.message}</Alert> : null}
      <input type="hidden" name="factorId" value={factorId} />
      <input type="hidden" name="next" value={next} />
      <TextField
        id="code"
        name="code"
        label="6-digit code"
        inputMode="numeric"
        autoComplete="one-time-code"
        pattern="[0-9]*"
        maxLength={7}
        required
      />
      <Button type="submit" loading={pending}>
        Verify
      </Button>
    </form>
  );
}

export function MfaEnroll({ next }: { next: string }) {
  const [enrollment, setEnrollment] = useState<EnrollState>({ status: 'idle' });
  const [starting, startTransition] = useTransition();

  if (enrollment.status === 'enrolling') {
    return (
      <div className="flex flex-col gap-6">
        <ol className="list-decimal space-y-2 ps-5 text-fg-secondary">
          <li>Open your authenticator app and add a new account.</li>
          <li>Scan this code, or type the setup key below.</li>
          <li>Enter the 6-digit code the app shows.</li>
        </ol>
        {/* The QR code is an SVG data URI generated by Supabase Auth. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={enrollment.qrCode}
          alt="QR code for your authenticator app"
          width={180}
          height={180}
          className="rounded-md border border-border bg-surface p-2"
        />
        <p className="text-sm text-muted">
          Setup key: <code className="break-all text-fg">{enrollment.secret}</code>
        </p>
        <MfaVerify factorId={enrollment.factorId} next={next} />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      {enrollment.status === 'error' ? <Alert tone="error">{enrollment.message}</Alert> : null}
      <Button
        type="button"
        loading={starting}
        onClick={() => startTransition(async () => setEnrollment(await startTotpEnrollment()))}
      >
        Set up authenticator app
      </Button>
    </div>
  );
}
