#!/usr/bin/env node
/* Content seed: content/spanish/level-*.json → seed/content.sql

     node scripts/build-seed.mjs
     npx wrangler d1 execute teacher-room --local  --file=seed/content.sql
     npx wrangler d1 execute teacher-room --remote --file=seed/content.sql

   Every statement is INSERT OR IGNORE, so running it again never overwrites
   what staff have edited in the admin area — it only fills in rows that are
   missing. The seven languages are always created; only Spanish is published.
   The other six start as Draft with no levels, ready for staff to build. */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const NOW = Date.UTC(2026, 8, 1);

/* Per-language settings. `normalize` holds the answer-checking defaults for
   the language; an exercise can override any of them. Nothing here removes a
   distinction a learner is expected to master: accents stay significant in
   Spanish, French, Italian and Greek, umlauts in German, and in Arabic only
   the optional short-vowel marks (harakat) and tatweel are ignored. */
export const LANGUAGES = [
  { id: 'es', name_he: 'ספרדית', name_native: 'Español', dir: 'ltr', status: 'published', sort: 1,
    font: "'Frank Ruhl Libre', Georgia, serif",
    chars: ['á', 'é', 'í', 'ó', 'ú', 'ü', 'ñ', '¿', '¡'],
    normalize: { accents: 'strict', stopwords: ['el', 'la', 'los', 'las', 'un', 'una', 'unos', 'unas', 'de', 'del', 'a', 'al', 'en', 'y', 'o', 'que', 'es', 'son', 'se', 'le', 'les', 'lo', 'su', 'sus', 'por', 'para', 'con', 'mi', 'mis', 'tu', 'tus', 'me', 'te', 'nos', 'muy', 'porque'] } },
  { id: 'en', name_he: 'אנגלית', name_native: 'English', dir: 'ltr', status: 'draft', sort: 2,
    font: "'Frank Ruhl Libre', Georgia, serif", chars: [],
    normalize: { accents: 'strict', stopwords: ['the', 'a', 'an', 'of', 'to', 'in', 'on', 'and', 'or', 'is', 'are', 'it', 'for', 'with', 'my', 'your', 'his', 'her', 'their', 'because'] } },
  { id: 'de', name_he: 'גרמנית', name_native: 'Deutsch', dir: 'ltr', status: 'draft', sort: 3,
    font: "'Frank Ruhl Libre', Georgia, serif", chars: ['ä', 'ö', 'ü', 'ß', 'Ä', 'Ö', 'Ü'],
    normalize: { accents: 'strict', eszett: 'strict', stopwords: [] } },
  { id: 'it', name_he: 'איטלקית', name_native: 'Italiano', dir: 'ltr', status: 'draft', sort: 4,
    font: "'Frank Ruhl Libre', Georgia, serif", chars: ['à', 'è', 'é', 'ì', 'ò', 'ù'],
    normalize: { accents: 'strict', stopwords: [] } },
  { id: 'fr', name_he: 'צרפתית', name_native: 'Français', dir: 'ltr', status: 'draft', sort: 5,
    font: "'Frank Ruhl Libre', Georgia, serif",
    chars: ['é', 'è', 'ê', 'ë', 'à', 'â', 'ç', 'î', 'ï', 'ô', 'û', 'ù', 'œ', '«', '»'],
    normalize: { accents: 'strict', stopwords: [] } },
  { id: 'ar', name_he: 'ערבית', name_native: 'العربية', dir: 'rtl', status: 'draft', sort: 6,
    font: "'Noto Naskh Arabic', 'Noto Sans Arabic', serif", chars: ['ء', 'آ', 'أ', 'إ', 'ؤ', 'ئ', 'ة', 'ى'],
    normalize: { harakat: 'ignore', tatweel: 'ignore', alef: 'strict', stopwords: [] } },
  { id: 'el', name_he: 'יוונית', name_native: 'Ελληνικά', dir: 'ltr', status: 'draft', sort: 7,
    font: "'Noto Serif', 'Noto Serif Greek', serif", chars: ['ά', 'έ', 'ή', 'ί', 'ό', 'ύ', 'ώ', 'ϊ', 'ϋ', 'ΐ', 'ΰ', 'ς'],
    normalize: { accents: 'strict', stopwords: [] } }
];

const q = v => v === null || v === undefined ? 'NULL'
  : typeof v === 'number' ? String(v)
  : "'" + String(v).replace(/'/g, "''") + "'";
const J = v => q(JSON.stringify(v));

function row(table, obj) {
  const cols = Object.keys(obj);
  return `INSERT OR IGNORE INTO ${table} (${cols.join(',')}) VALUES (${cols.map(c => obj[c]).join(',')});`;
}

function build() {
  const out = ['-- Generated by scripts/build-seed.mjs — do not edit by hand.'];
  for (const l of LANGUAGES) {
    out.push(row('languages', {
      id: q(l.id), name_he: q(l.name_he), name_native: q(l.name_native), dir: q(l.dir),
      status: q(l.status), sort: l.sort, font_stack: q(l.font), special_chars: J(l.chars),
      normalize: J(l.normalize), created_at: NOW, updated_at: NOW
    }));
  }
  let topicsN = 0, exN = 0;
  for (const n of [1, 2, 3]) {
    const file = join(ROOT, 'content', 'spanish', `level-${n}.json`);
    const d = JSON.parse(readFileSync(file, 'utf8'));
    const levelId = `es-${n}`;
    out.push(row('levels', {
      id: q(levelId), language_id: q('es'), number: n, name_he: q(d.title_he),
      name_target: q(d.title_target), cefr: q(d.cefr), description: q(d.description),
      status: q('published'), challenge_enabled: 1, rubric: J(d.rubric || []),
      created_at: NOW, updated_at: NOW
    }));
    const cycleOf = {};
    d.cycles.forEach((c, i) => {
      const id = `${levelId}-${c.key}`;
      c.topics.forEach(s => { cycleOf[s] = id; });
      out.push(row('cycles', {
        id: q(id), level_id: q(levelId), title_he: q(c.title_he), title_target: q(c.title_target),
        description: q(c.proposed ? 'קיבוץ ראשוני שהוצע בעת הייבוא מהחוברת — ניתן לשנות.' : ''),
        sort: i, created_at: NOW
      }));
    });
    d.topics.forEach((t, ti) => {
      topicsN++;
      const links = t.quizlet ? [{ label: 'כרטיסיות Quizlet של הנושא (אתר חיצוני)', url: t.quizlet }] : [];
      out.push(row('topics', {
        id: q(t.slug), level_id: q(levelId), cycle_id: q(cycleOf[t.slug] || null),
        title_he: q(t.title_he), title_target: q(t.title_target), objective: q(t.objective),
        objective_source: q(t.objective_source), skills: J(t.skills), grammar: J(t.grammar),
        explanation: J(t.explanation), vocab: J(t.vocab), self_check: J(t.self_check),
        links: J(links), status: q('published'),
        source_ref: q(t.unit ? `workbook L${n} unit ${String(t.unit).padStart(2, '0')}` : `workbook L${n} ${t.special}`),
        sort: t.unit || 100 + ti, created_at: NOW, updated_at: NOW
      }));
      t.exercises.forEach((e, i) => {
        exN++;
        out.push(row('exercises', {
          id: q(`${t.slug}-${String(i + 1).padStart(2, '0')}`), topic_id: q(t.slug), kind: q(e.kind),
          skill: q(e.skill), title: q(e.title), instructions: q(e.instructions), mode: q(e.mode),
          body: J(e.body), key_json: J(e.key), status: q('published'), source_ref: q(e.source_ref || ''),
          sort: i, created_at: NOW, updated_at: NOW
        }));
      });
    });
  }
  mkdirSync(join(ROOT, 'seed'), { recursive: true });
  writeFileSync(join(ROOT, 'seed', 'content.sql'), out.join('\n') + '\n');
  console.log(`seed/content.sql: 7 languages, 3 levels, ${topicsN} topics, ${exN} activities`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) build();
