#!/usr/bin/env node
/* LOCAL DEMONSTRATION ACCOUNTS — never run against the production database.

     node scripts/seed-demo.mjs            # writes seed/demo.sql (+ .dev.vars if missing)
     npm run demo                          # schema + content + demo accounts + wrangler dev

   Creates clearly labelled demo accounts in the LOCAL D1 so the platform can
   be tried end to end. Passwords and codes below are public on purpose: they
   only work against a local database seeded by this script, with the local
   pepper this script writes to .dev.vars. The script refuses to write SQL
   that targets anything else — it only produces a file; `npm run demo`
   applies it with --local. */

import { writeFileSync, existsSync, readFileSync, mkdirSync } from 'node:fs';
import { pbkdf2Sync, randomBytes, createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DEV_VARS = join(ROOT, '.dev.vars');
const DEFAULT_PEPPER = 'local-demo-pepper-not-for-production';

function readPepper() {
  if (!existsSync(DEV_VARS)) {
    writeFileSync(DEV_VARS,
      `# Local development only — generated by scripts/seed-demo.mjs\n` +
      `STUDENT_CODE_PEPPER=${DEFAULT_PEPPER}\nDEMO_MODE=1\n`);
    return DEFAULT_PEPPER;
  }
  const m = readFileSync(DEV_VARS, 'utf8').match(/^STUDENT_CODE_PEPPER=(.*)$/m);
  if (!m) throw new Error('.dev.vars exists but has no STUDENT_CODE_PEPPER — add one and re-run.');
  return m[1].trim();
}

const q = v => v === null || v === undefined ? 'NULL' : typeof v === 'number' ? String(v)
  : "'" + String(v).replace(/'/g, "''") + "'";

function pack(pass) {
  const salt = randomBytes(16);
  const hash = pbkdf2Sync(pass, salt, 100000, 32, 'sha256');
  return `pbkdf2$100000$${salt.toString('hex')}$${hash.toString('hex')}`;
}

export const DEMO = {
  staff: [
    { id: 'demo-admin', user: 'demo-admin', email: 'demo-admin@example.invalid', pass: 'demo-admin-2026', role: 'אדמין', name: 'הדגמה · אדמין' },
    { id: 'demo-pedagogy', user: 'demo-pedagogy', email: 'demo-pedagogy@example.invalid', pass: 'demo-pedagogy-2026', role: 'מנהל פדגוגי', name: 'הדגמה · מנהל פדגוגי' },
    { id: 'demo-office', user: 'demo-office', email: 'demo-office@example.invalid', pass: 'demo-office-2026', role: 'מנהלת קבלה', name: 'הדגמה · קבלה ורישום' },
    { id: 'demo-teacher', user: 'demo-teacher', email: 'demo-teacher@example.invalid', pass: 'demo-teacher-2026', role: 'מורה', name: 'הדגמה · מורה לספרדית', levels: ['es-1'] }
  ],
  students: [
    { id: 'demo-s1', name: 'הדגמה · תלמידה ברמה 1', code: 'DEMA-ESAA', levels: ['es-1'] },
    { id: 'demo-s2', name: 'הדגמה · תלמיד ברמה 2', code: 'DEMA-ESBB', levels: ['es-2'] },
    { id: 'demo-s12', name: 'הדגמה · תלמידה ברמות 1 ו־2', code: 'DEMA-ESCC', levels: ['es-1', 'es-2'] }
  ]
};

function build() {
  /* DEMO_PEPPER lets the test suite seed against its own throwaway pepper. */
  const pepper = process.env.DEMO_PEPPER || readPepper();
  const now = Date.now();
  const out = ['-- LOCAL DEMO ACCOUNTS — generated by scripts/seed-demo.mjs. Never apply to production.'];
  for (const s of DEMO.staff) {
    out.push(`INSERT OR REPLACE INTO staff_users (id,email,username,pass_hash,role,name,initials,active,must_change,created_at) VALUES (${q(s.id)},${q(s.email)},${q(s.user)},${q(pack(s.pass))},${q(s.role)},${q(s.name)},'הד',1,0,${now});`);
    for (const l of s.levels || []) out.push(`INSERT OR IGNORE INTO teacher_levels (teacher_id, level_id) VALUES (${q(s.id)},${q(l)});`);
  }
  for (const s of DEMO.students) {
    const norm = s.code.replace(/-/g, '');
    const hash = createHash('sha256').update(pepper + '$' + norm).digest('hex');
    out.push(`INSERT OR REPLACE INTO staff_users (id,email,username,pass_hash,role,name,initials,active,must_change,created_at) VALUES (${q(s.id)},${q(s.id + '@students.invalid')},NULL,'!',${q('תלמיד')},${q(s.name)},'הד',1,0,${now});`);
    out.push(`DELETE FROM student_codes WHERE user_id=${q(s.id)};`);
    out.push(`INSERT INTO student_codes (code_hash,user_id,issued_by,created_at) VALUES (${q(hash)},${q(s.id)},'demo-admin',${now});`);
    for (const l of s.levels) {
      out.push(`INSERT OR IGNORE INTO enrollments (id,user_id,level_id,status,started_at,created_by) VALUES (${q('en-' + s.id + '-' + l)},${q(s.id)},${q(l)},'active',${now},'demo-admin');`);
    }
  }
  mkdirSync(join(ROOT, 'seed'), { recursive: true });
  writeFileSync(process.env.DEMO_SQL_OUT || join(ROOT, 'seed', 'demo.sql'), out.join('\n') + '\n');
  console.log('seed/demo.sql written (LOCAL DEMO ONLY).');
  console.log('\nDemo sign-in (local only):');
  for (const s of DEMO.staff) console.log(`  staff   ${s.user.padEnd(14)} ${s.pass.padEnd(20)} ${s.role}`);
  for (const s of DEMO.students) console.log(`  student code ${s.code}   ${s.levels.join(', ')}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) build();
